server:
  service:
    type: ClusterIP
  extraArgs:
    - --insecure

configs:
  params:
    server.insecure: true

rbac:
  create: true

timeouts:
  reconciliation: 180s

dex:
  enabled: false

notifications:
  enabled: false

applicationSet:
  enabled: false

controller:
  replicas: 1

repoServer:
  replicas: 1
