resources:
  requests:
    memory: 64Mi
  limits:
    memory: 128Mi

persistence:
  enabled: false

adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.monitoring.svc.cluster.local
        access: proxy
        isDefault: true
